- name: create directory
  become: true
  file:
    path: /home/ubuntu/hoho
    state: directory
    mode: '0777'


- name: copy artifact
  copy: 
    src: artifact.tar.gz
    dest: /home/ubuntu/hoho

- name: copy artifact
  copy: 
    src: text.txt
    dest: /home/ubuntu/hoho



- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Executing node
  shell: |
    pm2 start npm -- start    