- name: create directory
  become: true
  file:
    path: ./direct
    state: directory


- name: copy artifact
  copy: 
    src: artifact.tar.gz
    dest: ./direct




- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Executing node
  shell: |
    pm2 start npm -- start    